# Generated by Django 5.1.7 on 2025-03-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular - Can’t delete members'), ('admin', 'Admin - Can delete members')], default='regular', max_length=10),
        ),
    ]
